In [3]:
# 1. Import numpy as np and print the version number. (5 Points)
import numpy as np
print(np.version)

2.1.2


In [25]:

# 2. Create a 1D array of numbers from 0 to 9. Desired output:
import numpy as np
output = np.arange(10)
output

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# 3. Import a dataset with numbers and texts keeping the text intact in python numpy. 
# Use the iris dataset available from https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.dataLinks to an external site..

import pandas as pd

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
df = pd.read_csv(url)
df_np = np.array(df)
df_np


array([[4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iris-setosa'],
       [5.1, 3.3, 1.7, 0.5, 'Iri

In [78]:
# 4. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset. 
# Use the iris dataset available from https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.dataLinks to an external site.. (20 Points)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
import pandas as pd
import numpy as np
petal = np.array(pd.read_csv(url))

a=0 # assign the position to for loop
for i in petal:
    if i[3] > 1.0:
        print(a) # print the index containing Value > 1.0
        break
    else: 
        a+=1


petal[49] # confirm the position No.49

49


array([7.0, 3.2, 4.7, 1.4, 'Iris-versicolor'], dtype=object)

In [86]:
# 5. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
import numpy as np
np.random.seed(100)
a = np.random.uniform(1,50, 20)

id = 0
for i in a.copy():
    if i >30:
        a[id] = 30.0
    elif i<10:
        a[id] =10.0
    id += 1
    
    
print(a)

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]
